i#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=2
#PBS -N 2017_cr_nojoin_no_golay_serial
#PBS -A d411-training
cd $PBS_O_WORKDIR
module load miniconda/python2
# loading virtualenv
echo "loading virtualenv"
source activate qiime1
# setting temporary directory
export TMPDIR=~/qiime_tmp

# Core diversity analysis
echo “corediversityanalysis”
time core_diversity_analyses.py -i otu_table_mc2_w_tax.biom -o coreanalysis -m classmap.tsv -t rep_set.tre -e 767

source deactivate
